import express, { Response } from 'express';
import { AIContextDoc } from '../models/AIContextDoc';
import { Task } from '../models/Task';
import { Message } from '../models/Message';
import { Channel } from '../models/Channel';
import { Workspace } from '../models/Workspace';
import { authenticate, AuthRequest } from '../middleware/auth';
import { requireWorkspaceMember, requireOmniOrOrgAdmin } from '../middleware/workspaceAuth';
import { createAuditLog } from '../services/auditService';

const router = express.Router();

// All routes require authentication
router.use(authenticate);

// Get project updates timeline
router.get('/:workspaceId/updates', requireWorkspaceMember, async (req: AuthRequest, res: Response) => {
  try {
    const { workspaceId } = req.params;
    const userId = req.userId!;

    // Get workspace
    const workspace = await Workspace.findById(workspaceId);
    if (!workspace) {
      return res.status(404).json({ error: 'Workspace not found' });
    }

    // Get AI summaries
    const summaries = await AIContextDoc.find({
      workspaceId,
      type: { $in: ['update_summary', 'task_summary', 'incident_report'] },
    })
      .sort({ createdAt: -1 })
      .limit(50)
      .lean();

    // Get recent tasks (for timeline)
    const recentTasks = await Task.find({
      workspaceId,
    })
      .sort({ createdAt: -1 })
      .limit(20)
      .populate('assigneeId', 'name')
      .lean();

    // Build timeline
    const timeline: any[] = [];

    // Add summaries
    for (const summary of summaries) {
      timeline.push({
        id: summary._id,
        type: 'ai_summary',
        summaryType: summary.type,
        text: summary.text,
        metadata: summary.metadata,
        createdAt: summary.createdAt,
      });
    }

    // Add task events
    for (const task of recentTasks) {
      timeline.push({
        id: task._id,
        type: 'task',
        action: task.status === 'done' ? 'completed' : task.status === 'todo' ? 'created' : 'updated',
        title: task.title,
        status: task.status,
        assignee: (task as any).assigneeId ? {
          name: (task as any).assigneeId.name,
        } : null,
        createdAt: task.createdAt,
      });
    }

    // Sort timeline by date
    timeline.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    // Calculate project health (simplified)
    const totalTasks = await Task.countDocuments({ workspaceId });
    const completedTasks = await Task.countDocuments({ workspaceId, status: 'done' });
    const inProgressTasks = await Task.countDocuments({ workspaceId, status: 'in_progress' });
    const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

    // Get next milestone (placeholder - in production, use milestone system)
    const nextMilestone = null; // TODO: Implement milestone tracking

    res.json({
      workspace: {
        _id: workspace._id,
        name: workspace.name,
      },
      health: {
        completionRate,
        totalTasks,
        completedTasks,
        inProgressTasks,
        nextMilestone,
      },
      timeline: timeline.slice(0, 50), // Limit to 50 most recent
      summaries: summaries.map(s => ({
        _id: s._id,
        type: s.type,
        text: s.text,
        metadata: s.metadata,
        createdAt: s.createdAt,
      })),
    });
  } catch (error: any) {
    console.error('Get updates error:', error);
    res.status(500).json({ error: error.message || 'Failed to get updates' });
  }
});

// Generate AI summary (Omni+ only)
router.post('/:workspaceId/updates/generate', requireWorkspaceMember, requireOmniOrOrgAdmin, async (req: AuthRequest, res: Response) => {
  try {
    const { workspaceId } = req.params;
    const userId = req.userId!;

    // Get workspace
    const workspace = await Workspace.findById(workspaceId);
    if (!workspace) {
      return res.status(404).json({ error: 'Workspace not found' });
    }

    // Get recent activity for summary
    const recentTasks = await Task.find({ workspaceId })
      .sort({ updatedAt: -1 })
      .limit(10)
      .lean();

    const recentMessages = await Message.find({
      workspaceId,
      createdAt: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) }, // Last 7 days
    })
      .sort({ createdAt: -1 })
      .limit(50)
      .lean();

    // Generate summary text (placeholder - in production, use AI/LLM)
    const summaryText = `Project Update Summary for ${workspace.name}

Recent Activity:
- ${recentTasks.length} tasks updated in the last period
- ${recentMessages.length} messages in workspace channels

Key Highlights:
${recentTasks.slice(0, 3).map((t: any) => `- ${t.title} (${t.status})`).join('\n')}

This is a placeholder summary. In production, this would be generated by an AI system using LangGraph or similar.

Generated on: ${new Date().toISOString()}`;

    // Create AI context document
    const aiDoc = new AIContextDoc({
      workspaceId,
      type: 'update_summary',
      sourceId: null,
      text: summaryText,
      embedding: null, // Placeholder until AI computes
      metadata: {
        generatedBy: userId.toString(),
        taskCount: recentTasks.length,
        messageCount: recentMessages.length,
        generatedAt: new Date().toISOString(),
      },
    });

    await aiDoc.save();

    // Audit log
    await createAuditLog({
      actorUserId: userId.toString(),
      action: 'update_summary_generated',
      resourceType: 'update',
      resourceId: aiDoc._id.toString(),
      detail: { workspaceId, type: 'update_summary' },
    });

    res.status(201).json({
      summary: {
        _id: aiDoc._id,
        type: aiDoc.type,
        text: aiDoc.text,
        metadata: aiDoc.metadata,
        createdAt: aiDoc.createdAt,
      },
      message: 'Summary generated successfully',
    });
  } catch (error: any) {
    console.error('Generate summary error:', error);
    res.status(500).json({ error: error.message || 'Failed to generate summary' });
  }
});

export default router;
